version: "3.2"

services:
  todofront:
    image: ghcr.io/sdcs-course/todofront/todofront:latest
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    networks:
      - todo-network
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.hostname == docker-node-3
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 512M

networks:
  todo-network:
    external: true
